#!/usr/bin/env python3
import sys, hashlib


file = open(sys.argv[1], 'r')
filecontents = file.read()
file.close()

print('{}  {}'.format(
    hashlib.md5(filecontents.encode()).hexdigest(),
    sys.argv[1]
))
